// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIy4mpMYBzi9n70R-VLWvwylkM0yn6mk',
    appId: '1:663814908880:web:22342acf44191894ab27d5',
    messagingSenderId: '663814908880',
    projectId: 'visitingcardscanner-b0511',
    authDomain: 'visitingcardscanner-b0511.firebaseapp.com',
    storageBucket: 'visitingcardscanner-b0511.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTRL3cCCXc_fUz-w0GcDfZWXuK-9yhR4',
    appId: '1:663814908880:android:5c2258cf71062e06ab27d5',
    messagingSenderId: '663814908880',
    projectId: 'visitingcardscanner-b0511',
    storageBucket: 'visitingcardscanner-b0511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YHZ95H2w-hpuYS3o5Ua2tB-F-3rIdMU',
    appId: '1:663814908880:ios:ac36de58e9f310f2ab27d5',
    messagingSenderId: '663814908880',
    projectId: 'visitingcardscanner-b0511',
    storageBucket: 'visitingcardscanner-b0511.firebasestorage.app',
    iosBundleId: 'com.example.visitingCardScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7YHZ95H2w-hpuYS3o5Ua2tB-F-3rIdMU',
    appId: '1:663814908880:ios:ac36de58e9f310f2ab27d5',
    messagingSenderId: '663814908880',
    projectId: 'visitingcardscanner-b0511',
    storageBucket: 'visitingcardscanner-b0511.firebasestorage.app',
    iosBundleId: 'com.example.visitingCardScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZIy4mpMYBzi9n70R-VLWvwylkM0yn6mk',
    appId: '1:663814908880:web:61f8cf728c17c8acab27d5',
    messagingSenderId: '663814908880',
    projectId: 'visitingcardscanner-b0511',
    authDomain: 'visitingcardscanner-b0511.firebaseapp.com',
    storageBucket: 'visitingcardscanner-b0511.firebasestorage.app',
  );
}
